const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE : 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',

    //admin position manage
    FETCH_POSITION_START : 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS : 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED : 'FETCH_POSITION_FAILED',

    // admin gender manage 
    FETCH_GENDER_START : 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS : 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED : 'FETCH_GENDER_FAILED',

    // admin role manage
    FETCH_ROLE_START : 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS : 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED : 'FETCH_ROLE_FAILED',

    // handle create new user from UserRedux Form
    FETCH_CREATE_NEW_USER_START : 'FETCH_CREATE_NEW_USER_START',
    FETCH_CREATE_NEW_USER_SUCCESS  : 'FETCH_CREATE_NEW_USER_SUCCESS',
    FETCH_CREATE_NEW_USER_FAILED : 'FETCH_CREATE_NEW_USER_FAILED',

    // handle get all user by redux 
    FETCH_ALL_USER_SUCCESS : 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED : 'FETCH_ALL_USER_FAILED',

    // handle delete user by redux
    DELETE_USER_SUCCESS : 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED : 'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED : 'EDIT_USER_FAILED',
});

export default actionTypes;